### PR TITLE
A14

### PR DESCRIPTION
**Pull request by robinsuri**

### CODE REVIEW

**Comment by robinsuri** [comment]
<script> function myFunction() { var hour = new Date().getHours(); var greeting; if (hour < 18) { greeting = "Good day"; } else { greeting = "Good evening"; } document.getElementById("demo").innerHTML = greeting; }

**Comment by robinsuri** [comment]
comment

**Comment by githubapptesting** [comment]
comment

**Comment by robinsuri** [comment]
gtm

**Comment by robinsuri** [comment]
gtm

**Comment by robinsuri** [comment]
gtm

**Pull request merged**
